# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'tansu'

[build]
image = 'ghcr.io/tansu-io/tansu:pr-165'

[env]
RUST_LOG = 'warn,tansu_server=debug,tansu_storage=debug,tansu_schema_registry=debug'
AWS_ENDPOINT = "https://fly.storage.tigris.dev"
ADVERTISED_LISTENER_URL = "tcp://${FLY_APP_NAME}.flycast:9092/"
CLUSTER_ID = "tansu-fly-tigris"
STORAGE_ENGINE = "s3://${BUCKET_NAME}"

[[services]]
protocol = 'tcp'
internal_port = 9092
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0

[checks]
[checks.tcp_listener]
grace_period = "30s"
interval = "15s"
port = 9092
timeout = "10s"
type = "tcp"

[metrics]
port = 9100
path = "/metrics"

[[services.ports]]
port = 9092

[[vm]]
memory = '256'
cpu_kind = 'shared'
cpus = 1
